"""
AI Reminder Agent
------------------
Generates a payment reminder message for an overdue invoice.

Tone escalates automatically based on how overdue the invoice is and how
many reminders have already been sent — mimicking how a real collections
analyst would communicate (polite nudge -> firm follow-up -> final notice).

If an ANTHROPIC_API_KEY environment variable is set, the message is
generated by Claude for natural, personalized language. If no key is
configured, a rule-based template is used instead so the project still
runs end-to-end with zero setup.
"""
import os
from .models import Invoice

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")


def _escalation_level(invoice: Invoice) -> str:
    days = invoice.days_overdue()
    if days <= 7:
        return "gentle"
    elif days <= 21:
        return "firm"
    else:
        return "final"


def _template_message(invoice: Invoice, level: str) -> str:
    templates = {
        "gentle": (
            f"Hi {invoice.customer_name},\n\n"
            f"This is a friendly reminder that invoice {invoice.invoice_number} "
            f"for ₹{invoice.amount:,.2f} was due on {invoice.due_date}. "
            f"It looks like it's still pending — could you please arrange payment "
            f"at your earliest convenience? Let us know if you need any help.\n\n"
            f"Thanks,\nAccounts Team"
        ),
        "firm": (
            f"Dear {invoice.customer_name},\n\n"
            f"Invoice {invoice.invoice_number} for ₹{invoice.amount:,.2f} is now "
            f"{invoice.days_overdue()} days overdue (due {invoice.due_date}). "
            f"Please process this payment within the next 3 business days to "
            f"avoid any disruption to your service. Reply to this email if there's "
            f"an issue we should know about.\n\n"
            f"Regards,\nAccounts Team"
        ),
        "final": (
            f"Dear {invoice.customer_name},\n\n"
            f"FINAL NOTICE: Invoice {invoice.invoice_number} for ₹{invoice.amount:,.2f} "
            f"is now {invoice.days_overdue()} days overdue. Despite {invoice.reminders_sent} "
            f"previous reminder(s), payment has not been received. Please settle this "
            f"invoice immediately to avoid escalation to our collections process.\n\n"
            f"Accounts Team"
        ),
    }
    return templates[level]


def _claude_message(invoice: Invoice, level: str) -> str:
    """Generate a reminder using Claude via the Anthropic API."""
    import requests

    tone_map = {
        "gentle": "polite and friendly, assuming it's just an oversight",
        "firm": "firm and professional, urging prompt action",
        "final": "serious final-notice tone, but still professional (no threats)",
    }

    prompt = (
        f"Write a short payment reminder email (under 120 words) with a "
        f"{tone_map[level]} tone.\n"
        f"Customer: {invoice.customer_name}\n"
        f"Invoice number: {invoice.invoice_number}\n"
        f"Amount due: ₹{invoice.amount:,.2f}\n"
        f"Due date: {invoice.due_date}\n"
        f"Days overdue: {invoice.days_overdue()}\n"
        f"Reminders already sent: {invoice.reminders_sent}\n"
        f"Sign off as 'Accounts Team'. Return only the email body."
    )

    response = requests.post(
        "https://api.anthropic.com/v1/messages",
        headers={
            "x-api-key": ANTHROPIC_API_KEY,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
        json={
            "model": "claude-sonnet-4-6",
            "max_tokens": 300,
            "messages": [{"role": "user", "content": prompt}],
        },
        timeout=15,
    )
    response.raise_for_status()
    data = response.json()
    return data["content"][0]["text"]


def generate_reminder(invoice: Invoice) -> dict:
    """Return the escalation level and a ready-to-send reminder message."""
    level = _escalation_level(invoice)

    if ANTHROPIC_API_KEY:
        try:
            message = _claude_message(invoice, level)
            source = "claude"
        except Exception:
            message = _template_message(invoice, level)
            source = "template_fallback"
    else:
        message = _template_message(invoice, level)
        source = "template"

    return {
        "invoice_number": invoice.invoice_number,
        "escalation_level": level,
        "days_overdue": invoice.days_overdue(),
        "message": message,
        "generated_by": source,
    }
